config/routes.rb
Rails.application.routes.draw do
  root 'beers#index'
  devise_for :users
  resources :beers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beer.rb
class Beer < ApplicationRecord
  #association
  belongs_to :user
  
  #model.save - validations get called before RAW SQL gets generated
  validates_presence_of :name, :style, :ibu, :alcohol
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #Devise
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #associations
  has_many :beers, dependent: :destroy

  validates_presence_of :first_name, :last_name, :age

  #instance method
  def cut_off?
    beers.count > 25 ? true : false
  end

  def full_name
    "#[first_name} #{last_name}"
  end

  #class method

  #callback

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  #redirects user to login page if not logged in
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  # override the devise default strong params
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :age])
  end
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  #this is how you skip before actions in rails
  #skip_before_action :authenticate_user!, only: [:index]

  before_action :set_beer, except: [:index, :new, :create]

  def index
    # OLD WAY
    #@beers = Beer.all
    flash[:notice] = 'Welcome to the beer garden!'
    @beers = current_user.beers
  end

  def show
  end

  def new
  end

  def create
    @beer = Beer.new(beer_params)
    if @beer.save
      redirect_to @beer, notice: 'Beer created successfully!'
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
    def set_beer
      # OLD NON SCOPED WAY
      # @beer = Beer.find(params[:id])

      @beer = current_user.beers.find(params[:id])
    end

    def beer_params
      params.require(:beer).permit(:name, :style, :ibu, :alcohol)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/views/beers/edit.html.erb
<h1>Beers#edit</h1>
<p>Find me in app/views/beers/edit.html.erb</p>

app/views/beers/index.html.erb
<h1>Beers For: <%= current_user.full_name %></h1>
<hr />
<div class='text-center'>
 <% if current_user.cut_off? %>
   <h3 class='danger-text'>Go home <%= current_user.full_name %>, You're drunk! </h3>
 <% else %>
  <%= link_to 'Grab A Beer', new_beer_path, class: 'btn btn-large btn-warning' %>

  <% if @beers.any? %>
   <div class='row'>
    <% @beers.each do |beer| %>
     <div class="jumbotron beer col-xs-12 col-sm-6">
       <h1 class='truncated-text'><%= beer.name %></h1>
       <%= link_to 'Show Beer', beer, class: 'btn btn-primary' %>
      </div>
   <% end %>
  </div>

<% else %>
  <h3> Get Drunk Dude! Grab a Beer!</h3>
<% end %>

app/views/beers/new.html.erb
<h1>Beers#new</h1>
<p>Find me in app/views/beers/new.html.erb</p>

app/views/beers/show.html.erb
<h1>Beers#show</h1>
<p>Find me in app/views/beers/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserBeers</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render(partial: 'layouts/shared/navbar') %>
    <%= render(partial: 'layouts/shared/flash') %>
    <%= yield %>
  </body>
</html>

app/views/layouts/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="flash <%= type %>"
   <%= message %>
  </div>
<% end %>

app/views/layouts/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'User Beers', root_path, class: 'navbar-brand' %>
      <!-- <a class="navbar-brand" href="#">User Beers</a> -->
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active">
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>